// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBFCUvhS3CJhzh5AFujK41KdEAQUxbnWdg',
//     appId: '1:978702071410:web:9f87442662c3d2b3fc34eb',
//     messagingSenderId: '978702071410',
//     projectId: 'udemy-proects',
//     authDomain: 'udemy-proects.firebaseapp.com',
//     storageBucket: 'udemy-proects.appspot.com',
//     measurementId: 'G-53JC7HS1ZZ',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDTvGtLjLhBOhjwt85-28sIqzYGMTxUC5g',
//     appId: '1:978702071410:android:f2d77df1ea5fa3b9fc34eb',
//     messagingSenderId: '978702071410',
//     projectId: 'udemy-proects',
//     storageBucket: 'udemy-proects.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCQqZCTATrXQfcmeIQcBZSTR0oo2wB2_cU',
//     appId: '1:978702071410:ios:28f613dffd084c4bfc34eb',
//     messagingSenderId: '978702071410',
//     projectId: 'udemy-proects',
//     storageBucket: 'udemy-proects.appspot.com',
//     androidClientId: '978702071410-g4baromqagd1kejtphsnorlk09d89i26.apps.googleusercontent.com',
//     iosBundleId: 'com.example.socialApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCQqZCTATrXQfcmeIQcBZSTR0oo2wB2_cU',
//     appId: '1:978702071410:ios:28256a959fb667bffc34eb',
//     messagingSenderId: '978702071410',
//     projectId: 'udemy-proects',
//     storageBucket: 'udemy-proects.appspot.com',
//     androidClientId: '978702071410-g4baromqagd1kejtphsnorlk09d89i26.apps.googleusercontent.com',
//     iosBundleId: 'com.example.socialApp.RunnerTests',
//   );
// }
